/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.Conexion;
import entidades.*;
import java.sql.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import logica.*;
import patrones.*;
import patrones.ListaEmpleados;

/**
 *
 * @author Lenovo
 */
public class FrmAdmi extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdmi
     */
    public FrmAdmi() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcodigoE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtpaterno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtmaterno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtciudad = new javax.swing.JTextField();
        txtcodigoA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbosucursal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblempleados = new javax.swing.JTable();
        btnRegustrarEmpleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btncobrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbgrau = new javax.swing.JRadioButton();
        rbsipan = new javax.swing.JRadioButton();
        rbchanchan = new javax.swing.JRadioButton();
        rbolivos = new javax.swing.JRadioButton();
        rbpardo = new javax.swing.JRadioButton();
        rbmisti = new javax.swing.JRadioButton();
        rbmachu = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        lblsucursal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnumclie = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(53, 51, 49));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Registrar Empleado");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Código Empleado");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txtcodigoE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtcodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ap. Paterno");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtpaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtpaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 160, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Ap. Materno");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        txtmaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 160, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Nombre");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 160, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Ciudad");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        txtdireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Dirección");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Usuario");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        txtclave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Clave");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtciudad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 160, -1));
        jPanel2.add(txtcodigoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Código de asignación");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sucursal");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        cbosucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sipan", "Chan Chan", "Los Olivos", "Pardo", "Misti", "Machupicchu", "Grau" }));
        jPanel2.add(cbosucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 120, -1));

        tblempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CodigoE", "Apellidos", "Nombre", "Ciudad", "Direccion", "Usuario", "Clave"
            }
        ));
        jScrollPane1.setViewportView(tblempleados);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 790, 130));

        btnRegustrarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegustrarEmpleado.setText("Registrar Empleado");
        btnRegustrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegustrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegustrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 180, 30));

        jTabbedPane1.addTab("Empleado", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Generar ganancia de interes mensual de las cuentas");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btngenerar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btngenerar.setText("Generar Interes mensual");
        btngenerar.setEnabled(false);
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });
        jPanel4.add(btngenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dolar.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 310, 260));

        jTabbedPane1.addTab("Interés Mensual", jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Cobrar Mantenimiento");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        btncobrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncobrar.setText("Cobrar Mantenimiento");
        btncobrar.setEnabled(false);
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });
        jPanel7.add(btncobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 210, 30));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-de-credito.png"))); // NOI18N
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jTabbedPane1.addTab("Cobrar Mantenimiento", jPanel7);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Reporte de Clientes por Sucursal");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mostrar por Sucursal:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        rbgrau.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbgrau);
        rbgrau.setText("Grau");
        rbgrau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbgrauActionPerformed(evt);
            }
        });
        jPanel6.add(rbgrau, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        rbsipan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbsipan);
        rbsipan.setText("Sipan");
        rbsipan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsipanActionPerformed(evt);
            }
        });
        jPanel6.add(rbsipan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        rbchanchan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbchanchan);
        rbchanchan.setText("Chan Chan");
        rbchanchan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbchanchanActionPerformed(evt);
            }
        });
        jPanel6.add(rbchanchan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        rbolivos.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbolivos);
        rbolivos.setText("Los Olivos");
        rbolivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbolivosActionPerformed(evt);
            }
        });
        jPanel6.add(rbolivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        rbpardo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbpardo);
        rbpardo.setText("Pardo");
        rbpardo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpardoActionPerformed(evt);
            }
        });
        jPanel6.add(rbpardo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        rbmisti.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbmisti);
        rbmisti.setText("Misti");
        rbmisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmistiActionPerformed(evt);
            }
        });
        jPanel6.add(rbmisti, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        rbmachu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbmachu);
        rbmachu.setText("Machupicchu");
        rbmachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmachuActionPerformed(evt);
            }
        });
        jPanel6.add(rbmachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Apellidos", "Nombres", "Dni", "Ciudad", "Dirección", "Telefono", "Email"
            }
        ));
        jScrollPane2.setViewportView(tblclientes);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 690, 160));

        lblsucursal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsucursal.setText("Lista de Clientes de la Sucursal ");
        jPanel6.add(lblsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Número de Clientes: ");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        txtnumclie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.add(txtnumclie, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 90, -1));

        jTabbedPane1.addTab("Reporte", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 3, 820, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 850, 450));

        jPanel5.setBackground(new java.awt.Color(101, 35, 55));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel3.setText("EUREKABANK");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 340, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_bank_building_60px.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 200));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_go_back_24px.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 950, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        fl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     private void llenarTabla() throws Exception{
        ListaEmpleados objecto = new ListaEmpleados() ;
        Iterator<Empleado> iterador = objecto.getLista().iterator();
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(columnas);
         
        while (iterador.hasNext()) {
            empleado = (Empleado) iterador.next()  ;
            fila[0] = empleado.getCodigoE();
            fila[1] = empleado.getPaterno() + empleado.getMaterno();
            fila[2] = empleado.getNombre();
            fila[3] = empleado.getCiudad();
            fila[4] = empleado.getDireccion();
            fila[5] = empleado.getUsuario();
            fila[6] = empleado.getClave();
            modelo.addRow(fila);
        }
        tblempleados.setModel(modelo);
    }  
      
    public void Limpiar() {
        txtcodigoE.setText(null);
        txtcodigoA.setText(null);
        txtciudad.setText(null);
        txtdireccion.setText(null);
        txtmaterno.setText(null);
        txtpaterno.setText(null);
        txtnombre.setText(null);
        txtusuario.setText(null);
        txtclave.setText(null);
    }
     public String getCodigoSucu(String nombre){
         String codigo="";
         if (nombre.equalsIgnoreCase("Sipan")) {
             codigo = "001";
         } else if (nombre.equalsIgnoreCase("Chan Chan")) {
             codigo = "002";
         } else if (nombre.equalsIgnoreCase("Los Olivos")) {
             codigo = "003";
         } else if (nombre.equalsIgnoreCase("Pardo")) {
             codigo = "004";
         } else if (nombre.equalsIgnoreCase("Misti")) {
             codigo = "005";
         } else if (nombre.equalsIgnoreCase("Machupicchu")) {
             codigo = "006";
         } else if (nombre.equalsIgnoreCase("Grau")) {
             codigo = "007";
         }
         return codigo;
     }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        try {
            llenarTabla();
            int diaHoy, mesHoy, añoHoy, año1;
            GregorianCalendar fechaActual = new GregorianCalendar();
            diaHoy = fechaActual.get(Calendar.DAY_OF_MONTH);
            mesHoy = fechaActual.get(Calendar.MONTH)+1;
            añoHoy = fechaActual.get(Calendar.YEAR);
            año1 = añoHoy - 1900;        
            fechaalta = new Date(año1, mesHoy -1,diaHoy);
            listaMovi = MovimientoBL.listarMovimiento(fechaalta);
            listaMovi1 = MovimientoBL.listarMovimiento1(fechaalta);
            if (listaMovi != null) {
                btngenerar.setEnabled(false);
            } else{
                btngenerar.setEnabled(true);
            }

            if (listaMovi1 != null) {
                btncobrar.setEnabled(false);
            } else{
                btncobrar.setEnabled(true);
            } 
        } catch (Exception ex) {
            Logger.getLogger(FrmAdmi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void btnRegustrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegustrarEmpleadoActionPerformed
        // TODO add your handling code here:
        int rpta, rpta1;
        codigoE = txtcodigoE.getText();
        paterno = txtpaterno.getText();
        materno = txtmaterno.getText();
        nombre = txtnombre.getText();
        ciudad = txtciudad.getText();
        direccion = txtdireccion.getText();
        usuario = txtusuario.getText();
        clave = txtclave.getText();
        asigcodigo = txtcodigoA.getText();
        sucucodigo = getCodigoSucu(cbosucursal.getSelectedItem().toString());
        int diaHoy, mesHoy, añoHoy, año1;
        GregorianCalendar fechaActual = new GregorianCalendar();
        diaHoy = fechaActual.get(Calendar.DAY_OF_MONTH);
        mesHoy = fechaActual.get(Calendar.MONTH)+1;
        añoHoy = fechaActual.get(Calendar.YEAR);
        año1 = añoHoy - 1900;
        fechaalta = new Date(año1, mesHoy -1,diaHoy);
        rpta = EmpleadoBL.insertarEmpleado(codigoE, paterno, materno, nombre, ciudad, direccion, usuario, clave);
        rpta1 = AsignadoBL.insertarAsignado(asigcodigo, sucucodigo, codigoE, fechaalta, null);
        Limpiar();
        txtcodigoE.requestFocus();
    }//GEN-LAST:event_btnRegustrarEmpleadoActionPerformed

    public void llenartabla(String sucunombre){
        modeloC = new DefaultTableModel();
        modeloC.setColumnIdentifiers(columnasC);
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_listarClientesSucursal(?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, sucunombre);
            rs = cs.executeQuery();
            while(rs.next()) {
                filaC[0] = rs.getString(1);
                filaC[1] = rs.getString(2) + " " + rs.getString(3);
                filaC[2] = rs.getString(4);
                filaC[3] = rs.getString(5);
                filaC[4] = rs.getString(6);
                filaC[5] = rs.getString(7);
                filaC[6] = rs.getString(8);
                filaC[7] = rs.getString(9);
                modeloC.addRow(filaC);
            }
            tblclientes.setModel(modeloC);
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null,ex.getMessage(),"Error",0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            }catch(SQLException ex) {
                showMessageDialog(null,ex.getMessage(),"Error",0);
            }
        }
    }
    
    private void rbsipanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsipanActionPerformed
        // TODO add your handling code here:
        if (rbsipan.isSelected()) {
            llenartabla(rbsipan.getText()); 
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbsipan.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbsipanActionPerformed

    private void rbchanchanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbchanchanActionPerformed
        // TODO add your handling code here:
        if (rbchanchan.isSelected()) {
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbchanchan.getText());
            llenartabla(rbchanchan.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbchanchanActionPerformed

    private void rbolivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbolivosActionPerformed
        // TODO add your handling code here:
        if (rbolivos.isSelected()) {
            llenartabla(rbolivos.getText());  
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbolivos.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbolivosActionPerformed

    private void rbpardoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpardoActionPerformed
        // TODO add your handling code here:
        if (rbpardo.isSelected()) {
            llenartabla(rbpardo.getText()); 
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbpardo.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbpardoActionPerformed

    private void rbmistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmistiActionPerformed
        // TODO add your handling code here:
        if (rbmisti.isSelected()) {
            llenartabla(rbmisti.getText());
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbmisti.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbmistiActionPerformed

    private void rbmachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmachuActionPerformed
        // TODO add your handling code here:
        if (rbmachu.isSelected()) {
            llenartabla(rbmachu.getText());
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbmachu.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbmachuActionPerformed

    private void rbgrauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbgrauActionPerformed
        // TODO add your handling code here:
        if (rbgrau.isSelected()) {
            llenartabla(rbgrau.getText());
            lblsucursal.setText("Lista de Clientes de la Sucursal "+rbgrau.getText());
            txtnumclie.setText(String.valueOf(tblclientes.getRowCount()));
        }
    }//GEN-LAST:event_rbgrauActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
        interesMensual();
    }//GEN-LAST:event_btngenerarActionPerformed

    public String getNumMovimiento(String codigoC){
        String num="0";
        try {            
            cn=Conexion.realizarConexion();
            String sql="{call sp_obtener_nummovimiento(?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, codigoC);
            rs = cs.executeQuery();
            while(rs.next()) {
                num = rs.getString(1);
                if (num == null) {
                    num = "0";
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null,ex.getMessage(),"Error",0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            }catch(SQLException ex) {
                showMessageDialog(null,ex.getMessage(),"Error",0);
            }
        }
        return num;
    }
    
    public void InteresMensual(String cuencodigo, float monto){
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_Interes_Mensual(?,?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, cuencodigo);
            cs.setFloat(2, monto);
            cs.executeUpdate();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: "+ex.toString());
        } finally {
            try {
                cs.close();
                cn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: "+ex.toString());
            }
        }
    }
    
    public void interesMensual(){
        int rpta;
        String rpta1;
        
        int diaHoy, mesHoy, añoHoy, año1;
        GregorianCalendar fechaActual = new GregorianCalendar();
        diaHoy = fechaActual.get(Calendar.DAY_OF_MONTH);
        mesHoy = fechaActual.get(Calendar.MONTH)+1;
        añoHoy = fechaActual.get(Calendar.YEAR);
        año1 = añoHoy - 1900;
        movifecha = new Date(año1, mesHoy -1,diaHoy);        
        listaCuen = CuentaBL.listarCuenta();   
        if (listaCuen != null) {
            iteradorCuen = listaCuen.iterator();            
            if (diaHoy == 1) {
                while (iteradorCuen.hasNext()){
                    cuenta = iteradorCuen.next();
                    cuencodigo = cuenta.getCuencodigo();
                    movinum = Integer.parseInt(getNumMovimiento(cuencodigo));
                    movinum++;
                    emplcodigo = cuenta.getEmplcreacuenta();
                    tipocodigo = "005";                    
                    if (cuenta.getMonecodigo().equalsIgnoreCase("01")) {
                        moviimporte = cuenta.getCuensaldo()*0.007f;
                    } else{
                        moviimporte = cuenta.getCuensaldo()*0.006f;
                    }
                    rpta = MovimientoBL.insertarMovimiento(cuencodigo, movinum, movifecha, emplcodigo, tipocodigo, moviimporte, null);
                    InteresMensual(cuencodigo, moviimporte);
                    btngenerar.setEnabled(false);
                }
                JOptionPane.showMessageDialog(null, "Se ha realizado el movimiento de interes mensual");
            }else{
                JOptionPane.showMessageDialog(null, "Hoy no se puede generar la ganancia del interes mensual");
            }
        }
        
    }
    
    public void Mantenimiento(String cuencodigo, float monto){
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_retiro(?,?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, cuencodigo);
            cs.setFloat(2, monto);
            cs.executeUpdate();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: "+ex.toString());
        } finally {
            try {
                cs.close();
                cn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: "+ex.toString());
            }
        }
    }
    
    public void cobrarMantenimiento(){
        int rpta;
        String rpta1;
        
        int diaHoy, mesHoy, añoHoy, año1;
        GregorianCalendar fechaActual = new GregorianCalendar();
        diaHoy = fechaActual.get(Calendar.DAY_OF_MONTH);
        mesHoy = fechaActual.get(Calendar.MONTH)+1;
        añoHoy = fechaActual.get(Calendar.YEAR);
        año1 = añoHoy - 1900;
        movifecha = new Date(año1, mesHoy -1,diaHoy);        
        listaCuen = CuentaBL.listarCuenta();   
        if (listaCuen != null) {
            iteradorCuen = listaCuen.iterator();            
            if (diaHoy == 1) {
                while (iteradorCuen.hasNext()){
                    cuenta = iteradorCuen.next();
                    cuencodigo = cuenta.getCuencodigo();
                    movinum = Integer.parseInt(getNumMovimiento(cuencodigo));
                    movinum++;
                    emplcodigo = cuenta.getEmplcreacuenta();
                    tipocodigo = "006";                    
                    if (cuenta.getMonecodigo().equalsIgnoreCase("01")) {
                        if (cuenta.getCuensaldo()<3500) {
                            moviimporte = 7.0f;
                            rpta = MovimientoBL.insertarMovimiento(cuencodigo, movinum, movifecha, emplcodigo, tipocodigo, moviimporte, null);
                            Mantenimiento(cuencodigo, moviimporte);  
                            btncobrar.setEnabled(false);
                        }
                        
                    } else{
                        if (cuenta.getCuensaldo()<1200) {
                            moviimporte = 2.5f;
                            rpta = MovimientoBL.insertarMovimiento(cuencodigo, movinum, movifecha, emplcodigo, tipocodigo, moviimporte, null);
                            Mantenimiento(cuencodigo, moviimporte);
                            btncobrar.setEnabled(false);
                        }
                    }
                                      
                }
                JOptionPane.showMessageDialog(null, "Se ha realizado el movimiento de Mantenimiento de cuenta");
            }else{
                JOptionPane.showMessageDialog(null, "Hoy no se puede cobrar mantenimiento");
            }
        }
        
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int cont = FrmLogin.cont;
        int diaHoy;
        GregorianCalendar fechaActual = new GregorianCalendar();
        diaHoy = fechaActual.get(Calendar.DAY_OF_MONTH);
        if (diaHoy==1) {
            JOptionPane.showMessageDialog(null, "Hoy se debe cobrar el mantenimiento y generar la ganancia del interes mensual en las cuentas");
//            btngenerar.setEnabled(true);
//            btncobrar.setEnabled(true);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        // TODO add your handling code here:
        cobrarMantenimiento();
    }//GEN-LAST:event_btncobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegustrarEmpleado;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btngenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbosucursal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblsucursal;
    private javax.swing.JRadioButton rbchanchan;
    private javax.swing.JRadioButton rbgrau;
    private javax.swing.JRadioButton rbmachu;
    private javax.swing.JRadioButton rbmisti;
    private javax.swing.JRadioButton rbolivos;
    private javax.swing.JRadioButton rbpardo;
    private javax.swing.JRadioButton rbsipan;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTable tblempleados;
    public static javax.swing.JTextField txtciudad;
    public static javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtcodigoA;
    public static javax.swing.JTextField txtcodigoE;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtmaterno;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnumclie;
    public static javax.swing.JTextField txtpaterno;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    FrmLogin fl = new FrmLogin();
    private Date fechaalta;
    private ArrayList<Empleado> listaE;
    private Empleado empleado;
    private Iterator<Empleado> iterador;
    private DefaultTableModel modelo;
    private String columnas[] = {"CódigoE", "Apellidos", "Nombres", "Ciudad", "Dirección", "Usuario", "Clave"};
    private Object fila[] = new Object[columnas.length];
    private String codigoE, paterno, materno, direccion, usuario, ciudad, clave, nombre;
    private String asigcodigo, sucucodigo;
    private String cuencodigo,emplcodigo,tipocodigo;
    private Date movifecha;
    private float moviimporte;
    private int movinum;
    private ArrayList<Movimiento> listaMovi;
    private ArrayList<Movimiento> listaMovi1;
    private ArrayList<Cuenta> listaCuen;
    private Iterator<Cuenta> iteradorCuen;
    private Cuenta cuenta;
    private ArrayList<Cliente> listaC;
    private Cliente cliente;
    private Iterator<Cliente> iteradorC;
    private DefaultTableModel modeloC;
    private String columnasC[] = {"CódigoC", "Apellidos", "Nombres", "DNI", "Ciudad", "Dirección", "Telefono", "Email"};
    private Object filaC[] = new Object[columnasC.length];
    private static Connection cn = null;
    private static CallableStatement cs = null;
    private static PreparedStatement ps = null;
    private static Statement st = null;
    private static ResultSet rs = null;
}
