/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.Conexion;
import entidades.*;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import logica.*;

/**
 *
 * @author Lenovo
 */
public class FrmCuenta extends javax.swing.JFrame {

    /**
     * Creates new form FrmCliente
     */
    public FrmCuenta() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TxtMaterno = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtDni = new javax.swing.JTextField();
        TxtCiudad = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnmostrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TxtPaterno = new javax.swing.JTextField();
        TxtCodigo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtcodigoCuenta = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtcodigoReferencia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtmoneda1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtmontodeposito = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtimpuesto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtmontofinal = new javax.swing.JTextField();
        txtmontoactual = new javax.swing.JTextField();
        btnRealizarMovimiento = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMovimientos1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtcodigocuen = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcodigoempl = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtfechacuen = new javax.swing.JTextField();
        txtmoneda = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtsucursal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        txtcantmov = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        cbomes = new javax.swing.JComboBox<>();
        cboaño = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnMostrarMoviPorMes = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMovimientos2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtcantmovmes = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(53, 51, 49));
        jPanel6.setMaximumSize(new java.awt.Dimension(220, 200));
        jPanel6.setMinimumSize(new java.awt.Dimension(220, 200));
        jPanel6.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Teléfono:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        TxtMaterno.setEnabled(false);
        jPanel1.add(TxtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, 30));

        TxtNombre.setEnabled(false);
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, 30));

        TxtDni.setEnabled(false);
        jPanel1.add(TxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 160, 30));

        TxtCiudad.setEnabled(false);
        jPanel1.add(TxtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 180, 30));

        TxtDireccion.setEnabled(false);
        jPanel1.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 180, 30));

        TxtTelefono.setEnabled(false);
        jPanel1.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 30));

        TxtEmail.setEnabled(false);
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Dirección:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ciudad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("E-mail:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        btnmostrar.setBackground(new java.awt.Color(101, 35, 55));
        btnmostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Código del Cliente:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        TxtPaterno.setEnabled(false);
        jPanel1.add(TxtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, 30));

        TxtCodigo.setEnabled(false);
        jPanel1.add(TxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, 30));

        btnActualizar.setBackground(new java.awt.Color(101, 35, 55));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar Datos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 150, 30));

        btnGuardar.setBackground(new java.awt.Color(101, 35, 55));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 110, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setText("Datos del Cliente");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jTabbedPane1.addTab("Datos del Cliente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Código de la cuenta");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtcodigoCuenta.setEnabled(false);
        jPanel2.add(txtcodigoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Código de la cuenta a depositar");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel2.add(txtcodigoReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 150, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Monto de la cuenta");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        txtmoneda1.setEnabled(false);
        jPanel2.add(txtmoneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 80, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Monto a depositar");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        txtmontodeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontodepositoKeyReleased(evt);
            }
        });
        jPanel2.add(txtmontodeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 150, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Impuesto");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        txtimpuesto.setEnabled(false);
        jPanel2.add(txtimpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 150, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Monto descuento de la cuenta");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtmontofinal.setEnabled(false);
        jPanel2.add(txtmontofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, -1));

        txtmontoactual.setEnabled(false);
        jPanel2.add(txtmontoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 80, -1));

        btnRealizarMovimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRealizarMovimiento.setText("Realizar Movimiento");
        btnRealizarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarMovimientoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRealizarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("Realizar Transferencia");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        tblMovimientos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número Movi", "Fecha", "Codigo Empleado", "Tipo Movi", "Importe", "Cuenta Referencia"
            }
        ));
        jScrollPane3.setViewportView(tblMovimientos1);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 730, 110));

        jTabbedPane1.addTab("Movimiento", jPanel2);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Código de la cuenta");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 23, -1, -1));

        txtcodigocuen.setEnabled(false);
        jPanel7.add(txtcodigocuen, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 21, 221, -1));

        txtestado.setEnabled(false);
        jPanel7.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 61, 220, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Estado de la cuenta");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 61, -1, -1));

        txtcodigoempl.setEnabled(false);
        jPanel7.add(txtcodigoempl, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 21, 159, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Código del empleado");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 23, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Fecha de creación");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 63, -1, -1));

        txtfechacuen.setEnabled(false);
        jPanel7.add(txtfechacuen, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 61, 159, -1));

        txtmoneda.setEnabled(false);
        jPanel7.add(txtmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 91, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Saldo actual");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtsaldo.setEnabled(false);
        jPanel7.add(txtsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 94, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Codigo de Sucursal");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 103, -1, -1));

        txtsucursal.setEnabled(false);
        jPanel7.add(txtsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 101, 159, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Movimientos");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número Movi", "Fecha", "Codigo Empleado", "Tipo Movi", "Importe", "Cuenta Referencia"
            }
        ));
        jScrollPane2.setViewportView(tblMovimientos);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 730, 150));

        txtcantmov.setEnabled(false);
        jPanel7.add(txtcantmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 158, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Cantidad Total de movimientos ");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTabbedPane1.addTab("Datos de la cuenta", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel8.add(cbomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        cboaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel8.add(cboaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Movimientos / Fecha");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel23.setText("Mes");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel21.setText("Año");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        btnMostrarMoviPorMes.setBackground(new java.awt.Color(101, 35, 55));
        btnMostrarMoviPorMes.setText("Mostrar Movimientos por mes");
        btnMostrarMoviPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMoviPorMesActionPerformed(evt);
            }
        });
        jPanel8.add(btnMostrarMoviPorMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 210, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Movimientos");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        tblMovimientos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número Movi", "Fecha", "Codigo Empleado", "Tipo Movi", "Importe", "Cuenta Referencia"
            }
        ));
        jScrollPane4.setViewportView(tblMovimientos2);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 730, 120));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Cantidad de movimiento por mes seleccionado");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        jPanel8.add(txtcantmovmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 70, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel33.setText("Reporte de Movimientos por Mes del Cliente");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jTabbedPane1.addTab("Reporte", jPanel8);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 810, 430));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 102, 830, 440));

        jPanel4.setBackground(new java.awt.Color(101, 35, 55));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel2.setText("EUREKABANK");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 340, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_bank_building_60px.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 200));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_go_back_24px.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 670, 140));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 950, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        fl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void activar(boolean estado) {
        TxtPaterno.setEnabled(estado);
        TxtMaterno.setEnabled(estado);
        TxtNombre.setEnabled(estado);
        TxtDni.setEnabled(estado);
        TxtCiudad.setEnabled(estado);
        TxtDireccion.setEnabled(estado);
        TxtTelefono.setEnabled(estado);
        TxtEmail.setEnabled(estado);
    }
    
    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        codigocuen = txtcodigocuen.getText();
        cliecodigo = CuentaBL.buscarClienteCuenta(codigocuen);
        lista = ClienteBL.obtenerCliente(cliecodigo);
        if(lista != null) {
            iterador = lista.iterator();
            cliente = iterador.next();
            cliecodigo = cliente.getCliecodigo();
            TxtCodigo.setText(cliente.getCliecodigo());
            TxtPaterno.setText(cliente.getCliecodigo());
            TxtPaterno.setText(cliente.getCliepaterno());
            TxtMaterno.setText(cliente.getCliematerno());
            TxtNombre.setText(cliente.getClienombre());
            TxtDni.setText(cliente.getCliedni());
            TxtCiudad.setText(cliente.getClieciudad());
            TxtDireccion.setText(cliente.getCliedireccion());
            TxtTelefono.setText(cliente.getClietelefono());
            TxtEmail.setText(cliente.getClieemail());
            activar(false);
        } else {
            JOptionPane.showMessageDialog(this, "El código no existe", "Resultado", 1);
            TxtPaterno.requestFocus();
        }
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        activar(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String respuesta;
        cliecodigo = TxtCodigo.getText();
        cliepaterno = TxtPaterno.getText();
        cliematerno = TxtMaterno.getText();
        clienombre = TxtNombre.getText();
        cliedireccion = TxtDireccion.getText();
        cliedni = TxtDni.getText();
        clieciudad = TxtCiudad.getText();
        clietelefono = TxtTelefono.getText();
        clieemail = TxtEmail.getText();
        respuesta = ClienteBL.actualizarCliente(cliecodigo, cliepaterno, cliematerno, clienombre, cliedni, clieciudad, cliedireccion, clietelefono, clieemail);
        JOptionPane.showMessageDialog(this, respuesta, "Resultado", 1);
        activar(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private String getMoneda(String codigo){
        String moneda="";
        if (codigo.equalsIgnoreCase("01")) {
            moneda = "Soles";
        } else{
            moneda = "Dolares";
        }
        return moneda;
    }
    
    public String getNumMovimiento(String codigoC){
        String num="0";
        try {            
            cn=Conexion.realizarConexion();
            String sql="{call sp_obtener_nummovimiento(?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, codigoC);
            rs = cs.executeQuery();
            while(rs.next()) {
                num = rs.getString(1);
                if (num == null) {
                    num = "0";
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null,ex.getMessage(),"Error",0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            }catch(SQLException ex) {
                showMessageDialog(null,ex.getMessage(),"Error",0);
            }
        }
        return num;
    }
    public String getNumMovimientoMes(String cuencodigo, Date fecha1, Date fecha2){
        String num="0";
        try {            
            cn=Conexion.realizarConexion();
            String sql="{call sp_obtener_cantmovpormes(?,?,?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, cuencodigo);
            cs.setDate(2, fecha1);
            cs.setDate(3, fecha2);
            rs = cs.executeQuery();
            while(rs.next()) {
                num = rs.getString(1);
                if (num == null) {
                    num = "0";
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null,ex.getMessage(),"Error",0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            }catch(SQLException ex) {
                showMessageDialog(null,ex.getMessage(),"Error",0);
            }
        }
        return num;
    }
    public void llenartabla(String cuencodigo){
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(columnas);
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_listar_movimientos(?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, cuencodigo);
            rs = cs.executeQuery();
            while(rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2) ;
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                modelo.addRow(fila);
            }
            tblMovimientos.setModel(modelo);
            tblMovimientos1.setModel(modelo);
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null,ex.getMessage(),"Error",0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            }catch(SQLException ex) {
                showMessageDialog(null,ex.getMessage(),"Error",0);
            }
        }
    }
    public void llenartablaMes(String cuencodigo, Date fecha1, Date fecha2){
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(columnas);
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_listar_movimientosMes(?,?,?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, cuencodigo);
            cs.setDate(2, fecha1);
            cs.setDate(3, fecha2);
            rs = cs.executeQuery();
            while(rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2) ;
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                modelo.addRow(fila);
            }
            tblMovimientos2.setModel(modelo);
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null,ex.getMessage(),"Error",0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            }catch(SQLException ex) {
                showMessageDialog(null,ex.getMessage(),"Error",0);
            }
        }
    }
    
    private void btnMostrarMoviPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMoviPorMesActionPerformed
        // TODO add your handling code here:
        mes = Integer.parseInt(cbomes.getSelectedItem().toString());
        año = Integer.parseInt(cboaño.getSelectedItem().toString());
        int año1 = año - 1900;
        fecha1=new Date(año1,mes-1,1);
        fecha2=new Date(año1,mes-1,31);
        llenartablaMes(txtcodigocuen.getText(), fecha1, fecha2);
        txtcantmovmes.setText(getNumMovimientoMes(txtcodigocuen.getText(), fecha1, fecha2));
    }//GEN-LAST:event_btnMostrarMoviPorMesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        codigocuen = txtcodigocuen.getText();
        cliecodigo = CuentaBL.buscarClienteCuenta(codigocuen);
        listaCuen = CuentaBL.obtenerCuenta(codigocuen);
        if (listaCuen != null) {
            iteradorCuen = listaCuen.iterator();
            cuenta = iteradorCuen.next();
            txtcodigoempl.setText(cuenta.getEmplcreacuenta());
            String moneda = getMoneda(cuenta.getMonecodigo());
            txtmoneda.setText(moneda);
            txtmoneda1.setText(moneda);
            txtfechacuen.setText(String.valueOf(cuenta.getCuenfechacreacion()));
            txtsaldo.setText(String.valueOf(cuenta.getCuensaldo()));
            txtmontoactual.setText(String.valueOf(cuenta.getCuensaldo()));
            txtsucursal.setText(cuenta.getSucucodigo());
            txtestado.setText(cuenta.getCuenestado());
            txtcantmov.setText(this.getNumMovimiento(codigocuen));
            llenartabla(txtcodigocuen.getText());
        } else {
            JOptionPane.showMessageDialog(this, "El código no existe", "Resultado", 1);
            TxtPaterno.requestFocus();
        }
    }//GEN-LAST:event_formWindowActivated

    public float getMontoRecibido(String codigocuen){
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_obtener_montorecibe(?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, codigocuen);
            rs = cs.executeQuery();
            while (rs.next()) {
                return rs.getFloat("cuensaldo");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            showMessageDialog(null, ex.getMessage(), "Error", 0);
        } finally {
            try {
                rs.close();
                cs.close();
                cn.close();
            } catch (SQLException ex) {
                showMessageDialog(null, ex.getMessage(), "Error", 0);
            }
        }
        return 0.0f;
    }
    
    private void txtmontodepositoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontodepositoKeyReleased
        // TODO add your handling code here:
        String impuesto = txtmontodeposito.getText();
        if (impuesto.equals("")==false && impuesto.matches("[0-9]*")) {
            int num = Integer.parseInt(impuesto);
            double imp = num*0.0008;
            txtimpuesto.setText(imp+"");
            txtmontofinal.setText((num+imp)+"");
        }
    }//GEN-LAST:event_txtmontodepositoKeyReleased

    public String Deposito(String codigoDa, String codigoRecibe, float montoda, float montorecibe){
        String mensaje = "Registro actualizado";
        try {
            cn = Conexion.realizarConexion();
            String sql = "{call sp_deposito(?,?,?,?)}";
            cs = cn.prepareCall(sql);
            cs.setString(1, codigoDa);
            cs.setString(2, codigoRecibe);
            cs.setFloat(3, montoda);
            cs.setFloat(4, montorecibe);
            cs.executeUpdate();
        } catch (ClassNotFoundException | SQLException ex) {
            mensaje = ex.getMessage();
        } finally {
            try {
                cs.close();
                cn.close();
            } catch (SQLException ex) {
                mensaje = ex.getMessage();
            }
        }
        return mensaje;
    }
    
    private String getMonedaCodigoC(String codigo){
        String moneda="";
        if (codigo.equalsIgnoreCase("01")) {
            moneda = "Soles";
        } else{
            moneda = "Dolares";
        }
        return moneda;
    }
    
    private void btnRealizarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarMovimientoActionPerformed
        // TODO add your handling code here:
        try {
            int rpta, rpta2;
            String rpta1;
            float montofinal;
            codigocuen = txtcodigoCuenta.getText();
            cuenreferencia = txtcodigoReferencia.getText();
            listaCuen1 = CuentaBL.obtenerCuenta(cuenreferencia);  
            movinum = parseInt(getNumMovimiento(codigocuen));
            movinum2 = parseInt(getNumMovimiento(cuenreferencia));
            movinum++;
            movinum2++;
            int diaHoy, mesHoy, añoHoy, año1;
            GregorianCalendar fechaActual = new GregorianCalendar();
            diaHoy = fechaActual.get(Calendar.DAY_OF_MONTH);
            mesHoy = fechaActual.get(Calendar.MONTH)+1;
            añoHoy = fechaActual.get(Calendar.YEAR);
            año1 = añoHoy - 1900;
            movifecha = new Date(año1, mesHoy -1,diaHoy);
            empl = txtcodigoempl.getText();
            tipocodigo = "009";
            tipocodigo2 = "008";
            moviimporte = Float.parseFloat(txtmontofinal.getText());
            montofinal = Float.parseFloat(txtmontodeposito.getText());
            if (txtcodigoReferencia.getText().isEmpty()) {
                txtcodigoReferencia.requestFocus();
            } else if(listaCuen1 == null){
                JOptionPane.showMessageDialog(null, "Código de cuenta destino no existe", "Error",0);
                txtcodigoReferencia.requestFocus();
            } else{
                iteradorCuen1 = listaCuen1.iterator();
                cuenta1 = iteradorCuen1.next();
                String codigomoneda2 = getMonedaCodigoC(cuenta1.getMonecodigo());
                if (moviimporte>Float.parseFloat(txtmontoactual.getText())) {
                    JOptionPane.showMessageDialog(null, "No se puede realizar el movimiento porque usted quiere depositar un monto mayor al que posee", "Error",0);
                    txtmontofinal.setText(null);
                    txtmontodeposito.setText(null);
                    txtimpuesto.setText(null);                    
                } else if(!codigomoneda2.equalsIgnoreCase(txtmoneda1.getText())){
                    JOptionPane.showMessageDialog(null, "No se puede realizar una tranferencia entre cuentas con diferentes tipo de monedas", "Error",0);
                    txtcodigoReferencia.requestFocus();
                } else{
                    rpta = MovimientoBL.insertarMovimiento(codigocuen, movinum, movifecha, empl, tipocodigo, moviimporte, cuenreferencia);
                    rpta2 = MovimientoBL.insertarMovimiento(cuenreferencia, movinum2, movifecha, empl, tipocodigo2, montofinal, null);
                    float montoRecibe = montofinal + this.getMontoRecibido(cuenreferencia);
                    float montoactual = Float.parseFloat(txtmontoactual.getText())-moviimporte;
                    rpta1=Deposito(codigocuen, cuenreferencia, montoactual, montoRecibe);
                    JOptionPane.showMessageDialog(null, "Transacción realizada con éxito ");
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos no válidos + excepcion: "+ e.toString());
        }
        
    }//GEN-LAST:event_btnRealizarMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCiudad;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtMaterno;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPaterno;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarMoviPorMes;
    private javax.swing.JButton btnRealizarMovimiento;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JComboBox<String> cboaño;
    private javax.swing.JComboBox<String> cbomes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTable tblMovimientos1;
    private javax.swing.JTable tblMovimientos2;
    private javax.swing.JTextField txtcantmov;
    private javax.swing.JTextField txtcantmovmes;
    public static javax.swing.JTextField txtcodigoCuenta;
    private javax.swing.JTextField txtcodigoReferencia;
    public static javax.swing.JTextField txtcodigocuen;
    private javax.swing.JTextField txtcodigoempl;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechacuen;
    private javax.swing.JTextField txtimpuesto;
    private javax.swing.JTextField txtmoneda;
    private javax.swing.JTextField txtmoneda1;
    private javax.swing.JTextField txtmontoactual;
    private javax.swing.JTextField txtmontodeposito;
    private javax.swing.JTextField txtmontofinal;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txtsucursal;
    // End of variables declaration//GEN-END:variables

    FrmLogin fl = new FrmLogin();
    Date fecha1, fecha2;
    int dia, mes , año;
    private String codigocuen = "";
    private String cliecodigo, cliepaterno, cliematerno, clienombre, cliedni, clieciudad, cliedireccion, clietelefono, clieemail;
    private String monecodigo, sucucodigo, empl, cuensaldo, cuenfecha, cuenestado, cuencontmov;
    private String tipocodigo, tipocodigo2, cuenreferencia;
    private int movinum, movinum2;
    private float moviimporte;
    private Date movifecha;
    private ArrayList<Cliente> lista;
    private Iterator<Cliente> iterador;
    private Cliente cliente;
    private ArrayList<Cuenta> listaCuen;
    private Iterator<Cuenta> iteradorCuen;
    private Cuenta cuenta;
    private ArrayList<Cuenta> listaCuen1;
    private Iterator<Cuenta> iteradorCuen1;
    private Cuenta cuenta1;
    private static Connection cn = null;
    private static CallableStatement cs = null;
    private static PreparedStatement ps = null;
    private static Statement st = null;
    private static ResultSet rs = null;
    private DefaultTableModel modelo;
    private String columnas[] = {"Número Movi", "fecha", "Código Empleado", "TipoMovi", "Importe", "Cuenta Referencia"};
    private Object fila[] = new Object[columnas.length];
}
